### ISSUE TITLE
HTTP streaming response

### ISSUE THREAD

**Issue by jyun-zalando** [zalando-stups/friboo#117]
Hi,

I'm working on make a HTTP streaming response,

But, it seems Ring/Jetty does not choose "chunk-size" based on reading.

https://github.com/ageldama/ring-time-http/blob/master/src/ring_time_http/core.clj#L36

https://github.com/ageldama/jetty-time-streaming/blob/master/src/main/java/org/zalando/jetty_time_streaming/TimeHandler.java#L58

Is is Jetty's issue?

Thank you.

**Comment by PetrGlad** [comment]
This looks more like a Jetty (not friboo) question. 
What do you want to achieve with this, is this just an exercise? If you are willing to keep alive additional thread just for response then it's probably better just to loop inside handler.

**Comment by jyun-zalando** [comment]
@PetrGlad Yes, I'm sorry. (I will create another ticket in ring repo) These repos are just for testing purpose, because I was working on HTTP streaming feature for _baby-nakadi_ implementation.

I just expected some reasonable workaround or proper way to implement HTTP streaming than just adjust output-buffer-size with Jetty.

Also, Yes, I agree with you, it just needed one loop inside handler, not another thread.
(I guess main reason for I wrote like this, because my "use-case" is just looks like this.)


Thanks!

**Comment by Otann** [comment]
I'm closing this, since there is no Friboo related changes required.
