### ISSUE TITLE
Is it possible to get rid of log messages?

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#43]
When the code is loaded (even for uberjar building), the following messages appear:

```
INFO  [main] o.e.j.u.log - Logging initialized @14782ms
WARN  [main] c.n.c.s.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
INFO  [main] c.n.c.s.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
INFO  [main] c.n.c.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@2f0765f7
```

Is it possible to make them appear when the system is started, not on class load?

**Comment by dryewo** [comment]
Apparently it's not possible, it happens during `HystrixMetricsStreamServlet` class static initialization when it's loaded (when REPL starts):
https://github.com/Netflix/Hystrix/blob/5370e7bb9da9471758a307fdd461fbe74098644d/hystrix-contrib/hystrix-metrics-event-stream/src/main/java/com/netflix/hystrix/contrib/metrics/eventstream/HystrixMetricsStreamServlet.java#L55

**Comment by filiagees** [comment]
@dryewo 
You can **remove this message from output** adding a:
`logging.level.com.netflix.config.sources.URLConfigurationSource=ERROR`
in your `application.properties` file.

Or using the -Dstyle, for example:
 `java -Dlogging.level.com.netflix.config.sources.URLConfigurationSource=ERROR -jar /path/to/your_app.jar`


To disable **dynamic configuration sources** you can add `-Darchaius.dynamicProperty.disableDefaultConfig=true`

Or:
 create the file `config.properties`

[ref](https://github.com/Netflix/Hystrix/issues/275#issuecomment-362513744)

**Comment by yuanbohan** [comment]
If you are using logback framework, you can simply add a logger in your configuration like this:
```
<logger name="com.netflix.config.sources" level="error"/>
```
