### ISSUE TITLE
When an exception is thrown during system start, it does not get cleaned up.

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#44]
This concerns only reloaded workflow.

For example, if I mess something up with the database and run `(reset)`, it throws an exception during DB component startup.
After that, I fix the issue and run `(reset)` again. Now it refuses to start, because the HTTP port is already taken, previous instance of Http component is still running somewhere. `(stop)` does not help. The only solution here is to restart the REPL, which takes ~20s.

Would be nice to have roll-back functionality.

**Comment by Otann** [comment]
Was covered in #97
