### ISSUE TITLE
Dependencies for HTTP component have to be specified twice

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#49]
First in the component definition:

``` clj
(def-http-component Http "api.yaml" [db tokens])
```

Then in the system map:

``` clj
(system/http-system-map configuration
                        map->Http [:db :tokens]
                        :db (db/make-db (:db configuration))
                        :tokens (oauth2/map->OAUth2TokenRefresher ...))
```

Maintaining these two places is error-prone and non-beginner-friendly.
This also relates to #48.

**Comment by lasomethingsomething** [comment]
Hey @dryewo, can we close this issue? It's from May 2016. 

Or, we could add a "Help Wanted" label.

**Comment by Otann** [comment]
Was covered in #97
