### ISSUE TITLE
Pull apart HTTP and API

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#51]
Currently notions of HTTP serving and API handling are complected together in the `def-http-component` and `http-system-map` functions. Clearly, there should be separate components:
- `Http` component takes care of serving HTTP requests on the configured port. Uses configuration with `:http-` prefix.
- `Api` component takes care of calling the corresponding handler functions according to the API spec. Uses application-specific configuration with `:api-` prefix.

**Comment by lasomethingsomething** [comment]
Hey @dryewo, can we close this issue? It's from May 2016. 

Or, we could add a "Help Wanted" label.

**Comment by Otann** [comment]
Closing this, was implemented in #97
