### ISSUE TITLE
Make middleware stack customizable

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#53]
Currently it is statically defined:
https://github.com/zalando-stups/friboo/blob/fbfedf39dea957c6f2b51c58d4bb2d4a9ad26b55/src/org/zalando/stups/friboo/system/http.clj#L162
Instead, we can introduce customization points, so that a user can add his own middleware to the existing stack.

**Comment by taojang** [comment]
Maybe using dependency graph between middlewares to express the phases would be worth considering

**Comment by PetrGlad** [comment]
It would be better to provide all building pieces to users so they can combine them as they see fit. Just put default list of middlewares into public var and make it default argument value for "middleware" so users can modify it and pass explicitly if they want.

**Comment by Otann** [comment]
Was implemented in #97
