### ISSUE TITLE
Need to dissoc "open_id" key from tokeninfo from audit logs

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/friboo#54]
here: https://github.com/zalando-stups/friboo/blob/fbfedf39dea957c6f2b51c58d4bb2d4a9ad26b55/src/org/zalando/stups/friboo/system/audit_log.clj#L69
"open_id" key contains JWT tokens and should not be logged

**Comment by hjacobs** [comment]
Still needs to be released in a new version on Maven central.
